# Change these first
owner: WPSDisaster # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: App
    url: https://app.wpsevac.com/health-check
  - name: CDN
    url: https://files-staging.wpsevac.com/images/facilities/W-1001/fac-1585692711-W-1001/1585692711hi-rise-pic.jpg
  - name: wpsevac.com
    url: https://wpsevac.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wpsevac.com
  # baseUrl: /your-repo-name
  logoUrl: https://app.wpsevac.com/img/buttons/grayscale/WPSePlan.png
  name: Status
  introTitle: "**WPS Evac** is the software designed to meet all your emergency management needs"
  introMessage: This status page monitors our services and reports on any issues we may be facing at this time.
  navbar:
    - title: Status
      href: /
    - title: WPS Evac
      href: https://wpsevac.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
